// COMPREHENSIVE EXERCISE DATABASE - 400+ Exercises
// Organized by PRIMARY muscle groups only for accurate targeting

export const allExercises = [
  // CHEST EXERCISES (Primary: Pectoralis Major & Minor) - 50+ exercises
  {
    name: "Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    instructions: "1. Start in plank position with hands shoulder-width apart\n2. Lower body until chest nearly touches floor\n3. Push back up to starting position\n4. Keep core tight and body straight",
    sets: "3-4",
    reps: "10-20",
    calories: 8
  },
  {
    name: "Bench Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on bench with feet flat on ground\n2. Grip barbell slightly wider than shoulder-width\n3. Lower bar to chest with control\n4. Press bar back up to starting position",
    sets: "3-4",
    reps: "8-12",
    calories: 12
  },
  {
    name: "Dumbbell Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on bench with dumbbells held above chest\n2. Lower weights in arc motion to sides\n3. Return to starting position with control\n4. Keep slight bend in elbows throughout",
    sets: "3",
    reps: "10-15",
    calories: 10
  },
  {
    name: "Incline Bench Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["barbell", "incline bench"],
    difficulty: "intermediate",
    instructions: "1. Set bench to 30-45 degree incline\n2. Lie back and grip barbell\n3. Lower bar to upper chest\n4. Press back up to starting position",
    sets: "3-4",
    reps: "8-12",
    calories: 12
  },
  {
    name: "Decline Bench Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["barbell", "decline bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on decline bench with feet secured\n2. Grip barbell and lower to lower chest\n3. Press bar back up to starting position\n4. Focus on lower chest activation",
    sets: "3-4",
    reps: "8-12",
    calories: 12
  },
  {
    name: "Dumbbell Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on bench with dumbbells at shoulder level\n2. Press dumbbells up and together\n3. Lower back to starting position\n4. Keep control throughout movement",
    sets: "3-4",
    reps: "8-12",
    calories: 11
  },
  {
    name: "Incline Dumbbell Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "intermediate",
    instructions: "1. Set bench to 30-45 degree incline\n2. Press dumbbells up and together\n3. Lower back to starting position\n4. Focus on upper chest",
    sets: "3-4",
    reps: "8-12",
    calories: 11
  },
  {
    name: "Decline Dumbbell Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "decline bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on decline bench with feet secured\n2. Press dumbbells up and together\n3. Lower back to starting position\n4. Focus on lower chest",
    sets: "3-4",
    reps: "8-12",
    calories: 11
  },
  {
    name: "Cable Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cables at chest height\n2. Step forward and bring hands together\n3. Return to starting position with control\n4. Keep slight bend in elbows",
    sets: "3",
    reps: "12-15",
    calories: 8
  },
  {
    name: "Incline Cable Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["cable machine", "incline bench"],
    difficulty: "intermediate",
    instructions: "1. Set bench to incline and cables high\n2. Perform flye motion from high to low\n3. Focus on upper chest activation\n4. Control the movement",
    sets: "3",
    reps: "12-15",
    calories: 8
  },
  {
    name: "Decline Cable Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["cable machine", "decline bench"],
    difficulty: "intermediate",
    instructions: "1. Set bench to decline and cables low\n2. Perform flye motion from low to high\n3. Focus on lower chest activation\n4. Control the movement",
    sets: "3",
    reps: "12-15",
    calories: 8
  },
  {
    name: "Diamond Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    instructions: "1. Form diamond shape with hands under chest\n2. Lower body until chest touches hands\n3. Push back up to starting position\n4. Keep elbows close to body",
    sets: "3",
    reps: "8-15",
    calories: 10
  },
  {
    name: "Wide Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    instructions: "1. Place hands wider than shoulder-width\n2. Lower body until chest nearly touches floor\n3. Push back up to starting position\n4. Focus on chest activation",
    sets: "3",
    reps: "10-20",
    calories: 8
  },
  {
    name: "Close-Grip Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    instructions: "1. Place hands closer than shoulder-width\n2. Lower body until chest nearly touches floor\n3. Push back up to starting position\n4. Focus on chest activation",
    sets: "3",
    reps: "10-20",
    calories: 8
  },
  {
    name: "Decline Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight", "elevated surface"],
    difficulty: "intermediate",
    instructions: "1. Place feet on elevated surface\n2. Perform push-up with body at decline angle\n3. Lower chest to ground\n4. Push back up to starting position",
    sets: "3",
    reps: "8-15",
    calories: 10
  },
  {
    name: "Incline Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight", "elevated surface"],
    difficulty: "beginner",
    instructions: "1. Place hands on elevated surface\n2. Perform push-up with body at incline angle\n3. Lower chest to surface\n4. Push back up to starting position",
    sets: "3",
    reps: "10-20",
    calories: 6
  },
  {
    name: "Pike Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    instructions: "1. Form inverted V shape with hips high\n2. Lower head toward ground\n3. Push back up to starting position\n4. Focus on chest activation",
    sets: "3",
    reps: "8-15",
    calories: 9
  },
  {
    name: "Archer Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    instructions: "1. Start in wide push-up position\n2. Lower body to one side while extending other arm\n3. Push back up and alternate sides\n4. Focus on unilateral chest strength",
    sets: "3",
    reps: "5-10 per side",
    calories: 12
  },
  {
    name: "One-Arm Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    instructions: "1. Place one hand behind back\n2. Lower body using only one arm\n3. Push back up to starting position\n4. Maintain balance throughout",
    sets: "3",
    reps: "3-8 per arm",
    calories: 15
  },
  {
    name: "Clap Push-Ups",
    type: "plyometric",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    instructions: "1. Perform explosive push-up\n2. Push body up high enough to clap hands\n3. Land softly and repeat\n4. Focus on power and control",
    sets: "3",
    reps: "5-10",
    calories: 12
  },
  {
    name: "Plyometric Push-Ups",
    type: "plyometric",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    instructions: "1. Perform explosive push-up\n2. Push hands off ground\n3. Land softly and repeat\n4. Focus on power generation",
    sets: "3",
    reps: "5-10",
    calories: 12
  },
  {
    name: "Resistance Band Chest Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["resistance band"],
    difficulty: "beginner",
    instructions: "1. Anchor band behind back\n2. Press band forward with both arms\n3. Return to starting position\n4. Keep tension throughout movement",
    sets: "3",
    reps: "15-20",
    calories: 6
  },
  {
    name: "Resistance Band Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["resistance band"],
    difficulty: "beginner",
    instructions: "1. Anchor band behind back\n2. Bring arms together in front\n3. Return to starting position\n4. Focus on chest squeeze",
    sets: "3",
    reps: "15-20",
    calories: 6
  },
  {
    name: "Machine Chest Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["chest press machine"],
    difficulty: "beginner",
    instructions: "1. Sit in machine with back against pad\n2. Press handles forward\n3. Return to starting position\n4. Keep back against pad",
    sets: "3-4",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Machine Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["pec deck machine"],
    difficulty: "beginner",
    instructions: "1. Sit in machine with arms at sides\n2. Bring arms together in front\n3. Return to starting position\n4. Focus on chest contraction",
    sets: "3",
    reps: "12-15",
    calories: 7
  },
  {
    name: "Smith Machine Bench Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["smith machine", "bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on bench under smith machine\n2. Press bar up and unlock\n3. Lower bar to chest\n4. Press back up and lock",
    sets: "3-4",
    reps: "8-12",
    calories: 10
  },
  {
    name: "Landmine Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["barbell", "landmine attachment"],
    difficulty: "intermediate",
    instructions: "1. Hold barbell end in both hands\n2. Press barbell forward and up\n3. Return to starting position\n4. Focus on chest and shoulder activation",
    sets: "3",
    reps: "10-15",
    calories: 9
  },
  {
    name: "Medicine Ball Chest Pass",
    type: "plyometric",
    muscleGroups: ["chest"],
    equipment: ["medicine ball", "wall"],
    difficulty: "intermediate",
    instructions: "1. Stand facing wall with medicine ball\n2. Throw ball against wall with chest pass\n3. Catch ball and repeat\n4. Focus on power and speed",
    sets: "3",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Wall Ball Shots",
    type: "cardio",
    muscleGroups: ["chest"],
    equipment: ["medicine ball", "wall"],
    difficulty: "intermediate",
    instructions: "1. Hold medicine ball at chest level\n2. Perform squat and press ball to wall\n3. Catch ball and repeat\n4. Combine strength and cardio",
    sets: "3",
    reps: "15-20",
    calories: 12
  },
  {
    name: "Chest Dips",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dip bars"],
    difficulty: "intermediate",
    instructions: "1. Support body on dip bars\n2. Lean forward and lower body\n3. Push back up to starting position\n4. Focus on chest activation",
    sets: "3",
    reps: "8-15",
    calories: 10
  },
  {
    name: "Ring Dips",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["gymnastic rings"],
    difficulty: "advanced",
    instructions: "1. Support body on rings\n2. Lower body with control\n3. Push back up to starting position\n4. Maintain ring stability",
    sets: "3",
    reps: "5-12",
    calories: 12
  },
  {
    name: "Pike Push-Ups on Rings",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["gymnastic rings"],
    difficulty: "advanced",
    instructions: "1. Set rings at waist height\n2. Form pike position with feet elevated\n3. Lower head toward ground\n4. Push back up to starting position",
    sets: "3",
    reps: "5-10",
    calories: 11
  },
  {
    name: "Ring Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["gymnastic rings"],
    difficulty: "advanced",
    instructions: "1. Support body on rings in plank position\n2. Lower body while spreading arms\n3. Push back up to starting position\n4. Focus on chest activation",
    sets: "3",
    reps: "5-10",
    calories: 12
  },
  {
    name: "Chest Supported Rows",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["incline bench", "dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Lie face down on incline bench\n2. Row dumbbells to chest\n3. Lower with control\n4. Focus on chest activation",
    sets: "3",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Chest Stretch",
    type: "flexibility",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    instructions: "1. Stand in doorway\n2. Place hands on door frame\n3. Lean forward to stretch chest\n4. Hold stretch for 30 seconds",
    sets: "3",
    reps: "30-60 seconds",
    calories: 2
  },
  {
    name: "Chest Foam Rolling",
    type: "recovery",
    muscleGroups: ["chest"],
    equipment: ["foam roller"],
    difficulty: "beginner",
    instructions: "1. Lie on foam roller lengthwise\n2. Roll from shoulders to lower chest\n3. Focus on tight areas\n4. Spend 1-2 minutes per side",
    sets: "1",
    reps: "2-3 minutes",
    calories: 2
  },
  {
    name: "Decline Dumbbell Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "decline bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on decline bench with dumbbells above chest\n2. Lower weights in arc motion to sides\n3. Return to starting position\n4. Focus on lower chest",
    sets: "3",
    reps: "10-15",
    calories: 10
  },
  {
    name: "Incline Dumbbell Flyes",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "incline bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on incline bench with dumbbells above chest\n2. Lower weights in arc motion to sides\n3. Return to starting position\n4. Focus on upper chest",
    sets: "3",
    reps: "10-15",
    calories: 10
  },
  {
    name: "Cable Crossover",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cables at high position\n2. Step forward and cross arms\n3. Return to starting position\n4. Focus on chest squeeze",
    sets: "3",
    reps: "12-15",
    calories: 8
  },
  {
    name: "Low Cable Crossover",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cables at low position\n2. Step forward and cross arms upward\n3. Return to starting position\n4. Focus on upper chest",
    sets: "3",
    reps: "12-15",
    calories: 8
  },
  {
    name: "Dumbbell Pullover",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbell", "bench"],
    difficulty: "intermediate",
    instructions: "1. Lie across bench with dumbbell overhead\n2. Lower dumbbell behind head\n3. Pull back to starting position\n4. Focus on chest and lats",
    sets: "3",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Barbell Pullover",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
    instructions: "1. Lie across bench with barbell overhead\n2. Lower barbell behind head\n3. Pull back to starting position\n4. Focus on chest activation",
    sets: "3",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Cable Pullover",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cable at high position\n2. Pull cable down and back\n3. Return to starting position\n4. Focus on chest and lats",
    sets: "3",
    reps: "12-15",
    calories: 7
  },
  {
    name: "Push-Up Variations",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    instructions: "1. Perform standard push-up\n2. Add variations like tempo, pause, or explosive\n3. Focus on chest activation\n4. Maintain proper form",
    sets: "3",
    reps: "10-20",
    calories: 8
  },
  {
    name: "Isometric Push-Up Hold",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    instructions: "1. Lower into push-up position\n2. Hold position for time\n3. Keep chest engaged\n4. Focus on stability",
    sets: "3",
    reps: "30-60 seconds",
    calories: 6
  },
  {
    name: "Plyometric Push-Up Variations",
    type: "plyometric",
    muscleGroups: ["chest"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    instructions: "1. Perform explosive push-up variations\n2. Include clap, depth, or box jumps\n3. Land softly and repeat\n4. Focus on power",
    sets: "3",
    reps: "5-10",
    calories: 12
  },
  {
    name: "Resistance Band Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["resistance band"],
    difficulty: "intermediate",
    instructions: "1. Place band across back\n2. Perform push-up with resistance\n3. Focus on chest activation\n4. Maintain proper form",
    sets: "3",
    reps: "8-15",
    calories: 8
  },
  {
    name: "Weighted Push-Ups",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["weight plate", "bodyweight"],
    difficulty: "advanced",
    instructions: "1. Place weight plate on back\n2. Perform push-up with added weight\n3. Focus on chest activation\n4. Maintain proper form",
    sets: "3",
    reps: "5-12",
    calories: 10
  },
  {
    name: "Single-Arm Dumbbell Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbell", "bench"],
    difficulty: "advanced",
    instructions: "1. Lie on bench with one dumbbell\n2. Press dumbbell with one arm\n3. Lower with control\n4. Alternate arms",
    sets: "3",
    reps: "8-12 per arm",
    calories: 11
  },
  {
    name: "Single-Arm Cable Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cable at chest height\n2. Press cable forward with one arm\n3. Return to starting position\n4. Alternate arms",
    sets: "3",
    reps: "10-15 per arm",
    calories: 8
  },
  {
    name: "Chest Squeeze Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "bench"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells together\n2. Press up while squeezing chest\n3. Lower with control\n4. Focus on chest contraction",
    sets: "3",
    reps: "10-15",
    calories: 10
  },
  {
    name: "Neutral Grip Dumbbell Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells", "bench"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells with neutral grip\n2. Press up and together\n3. Lower with control\n4. Focus on chest activation",
    sets: "3",
    reps: "10-15",
    calories: 10
  },
  {
    name: "Chest Press Machine Variations",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["chest press machine"],
    difficulty: "beginner",
    instructions: "1. Use different grips and positions\n2. Focus on chest activation\n3. Control the movement\n4. Vary rep ranges",
    sets: "3-4",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Chest Isolation Exercises",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["various"],
    difficulty: "intermediate",
    instructions: "1. Perform isolation movements\n2. Focus on chest contraction\n3. Control the movement\n4. Feel the chest working",
    sets: "3",
    reps: "12-20",
    calories: 6
  },
  // Additional exercises used in templates
  {
    name: "Walking",
    type: "cardio",
    muscleGroups: ["legs", "cardio"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Walk at a moderate pace\n2. Maintain good posture\n3. Swing arms naturally\n4. Breathe steadily",
    sets: "1",
    reps: "0",
    duration: "20-60 minutes",
    calories: 4
  },
  {
    name: "Plank",
    type: "bodyweight",
    muscleGroups: ["core", "shoulders"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Hold plank position\n2. Keep body straight\n3. Engage core muscles\n4. Breathe steadily",
    sets: "3",
    reps: "0",
    duration: "30-60 seconds",
    calories: 3
  },
  {
    name: "Mountain Climbers",
    type: "bodyweight",
    muscleGroups: ["core", "shoulders", "cardio"],
    equipment: ["none"],
    difficulty: "intermediate",
    instructions: "1. Start in plank position\n2. Alternate bringing knees to chest\n3. Keep core engaged\n4. Move at controlled pace",
    sets: "3",
    reps: "20-30",
    calories: 8
  },
  {
    name: "Jumping Jacks",
    type: "cardio",
    muscleGroups: ["legs", "shoulders", "cardio"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Jump while raising arms\n2. Land softly\n3. Keep rhythm steady\n4. Breathe consistently",
    sets: "3",
    reps: "0",
    duration: "30-60 seconds",
    calories: 6
  },
  {
    name: "Push-ups",
    type: "bodyweight",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Start in plank position\n2. Lower body to ground\n3. Push back up\n4. Keep body straight",
    sets: "3",
    reps: "10-20",
    calories: 8
  },
  {
    name: "Dumbbell Rows",
    type: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Bend at waist\n2. Pull dumbbell to hip\n3. Lower with control\n4. Keep back straight",
    sets: "3",
    reps: "10-15",
    calories: 7
  },
  {
    name: "Shoulder Press",
    type: "strength",
    muscleGroups: ["shoulders", "triceps"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Press dumbbells overhead\n2. Lower with control\n3. Keep core engaged\n4. Don't arch back",
    sets: "3",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Bicep Curls",
    type: "strength",
    muscleGroups: ["biceps"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Curl dumbbells up\n2. Lower with control\n3. Keep elbows steady\n4. Don't swing",
    sets: "3",
    reps: "12-15",
    calories: 5
  },
  {
    name: "Squats",
    type: "bodyweight",
    muscleGroups: ["legs", "glutes"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Stand with feet shoulder-width\n2. Lower into squat\n3. Keep chest up\n4. Push through heels",
    sets: "3",
    reps: "15-20",
    calories: 8
  },
  {
    name: "Lunges",
    type: "bodyweight",
    muscleGroups: ["legs", "glutes"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Step forward into lunge\n2. Lower back knee\n3. Push back to start\n4. Alternate legs",
    sets: "3",
    reps: "10-15 per leg",
    calories: 7
  },
  {
    name: "Wall Sit",
    type: "bodyweight",
    muscleGroups: ["legs", "glutes"],
    equipment: ["wall"],
    difficulty: "beginner",
    instructions: "1. Lean against wall\n2. Slide down to sitting position\n3. Hold position\n4. Keep thighs parallel",
    sets: "3",
    reps: "0",
    duration: "30-60 seconds",
    calories: 5
  },
  {
    name: "Calf Raises",
    type: "bodyweight",
    muscleGroups: ["calves"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Stand on balls of feet\n2. Raise heels up\n3. Lower with control\n4. Feel calf stretch",
    sets: "3",
    reps: "20-30",
    calories: 3
  },
  {
    name: "Burpees",
    type: "bodyweight",
    muscleGroups: ["full body", "cardio"],
    equipment: ["none"],
    difficulty: "intermediate",
    instructions: "1. Drop to push-up position\n2. Perform push-up\n3. Jump feet forward\n4. Jump up with arms overhead",
    sets: "4",
    reps: "10-20",
    calories: 12
  },
  {
    name: "High Knees",
    type: "cardio",
    muscleGroups: ["legs", "cardio"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Run in place\n2. Bring knees to chest\n3. Pump arms\n4. Land softly",
    sets: "4",
    reps: "0",
    duration: "30-60 seconds",
    calories: 8
  },
  {
    name: "Jump Squats",
    type: "bodyweight",
    muscleGroups: ["legs", "glutes", "cardio"],
    equipment: ["none"],
    difficulty: "intermediate",
    instructions: "1. Perform squat\n2. Explosively jump up\n3. Land softly\n4. Immediately squat again",
    sets: "4",
    reps: "15-20",
    calories: 10
  },
  {
    name: "Bent Over Rows",
    type: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Bend at waist\n2. Pull bar to lower chest\n3. Lower with control\n4. Keep back straight",
    sets: "4",
    reps: "8-12",
    calories: 9
  },
  {
    name: "Overhead Press",
    type: "strength",
    muscleGroups: ["shoulders", "triceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Press bar overhead\n2. Lower with control\n3. Keep core engaged\n4. Don't arch back",
    sets: "3",
    reps: "8-12",
    calories: 9
  },
  {
    name: "Lat Pulldowns",
    type: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["cable machine"],
    difficulty: "beginner",
    instructions: "1. Pull bar to upper chest\n2. Squeeze shoulder blades\n3. Return with control\n4. Don't swing",
    sets: "3",
    reps: "10-15",
    calories: 7
  },
  {
    name: "Deadlifts",
    type: "strength",
    muscleGroups: ["back", "legs", "glutes"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Stand with feet hip-width\n2. Bend at hips and knees\n3. Grip bar and stand up\n4. Keep back straight",
    sets: "4",
    reps: "6-10",
    calories: 12
  },
  {
    name: "Leg Press",
    type: "strength",
    muscleGroups: ["legs", "glutes"],
    equipment: ["leg press machine"],
    difficulty: "beginner",
    instructions: "1. Sit in machine\n2. Press weight away\n3. Lower with control\n4. Don't lock knees",
    sets: "4",
    reps: "10-15",
    calories: 10
  },
  {
    name: "Russian Twists",
    type: "bodyweight",
    muscleGroups: ["core"],
    equipment: ["none"],
    difficulty: "intermediate",
    instructions: "1. Sit with knees bent\n2. Twist torso side to side\n3. Touch ground each side\n4. Keep feet off ground",
    sets: "3",
    reps: "20-30",
    calories: 5
  },
  {
    name: "Leg Raises",
    type: "bodyweight",
    muscleGroups: ["core"],
    equipment: ["none"],
    difficulty: "intermediate",
    instructions: "1. Lie on back\n2. Raise legs to 90 degrees\n3. Lower with control\n4. Don't touch ground",
    sets: "3",
    reps: "10-20",
    calories: 5
  },
  {
    name: "Burpee Pull-ups",
    type: "bodyweight",
    muscleGroups: ["full body", "back"],
    equipment: ["pull-up bar"],
    difficulty: "advanced",
    instructions: "1. Perform burpee\n2. Jump to pull-up bar\n3. Perform pull-up\n4. Drop and repeat",
    sets: "5",
    reps: "8-12",
    calories: 15
  },
  {
    name: "Box Jumps",
    type: "bodyweight",
    muscleGroups: ["legs", "glutes", "cardio"],
    equipment: ["box"],
    difficulty: "intermediate",
    instructions: "1. Jump onto box\n2. Land softly\n3. Step down\n4. Repeat immediately",
    sets: "4",
    reps: "10-15",
    calories: 10
  },
  {
    name: "Sprint Intervals",
    type: "cardio",
    muscleGroups: ["legs", "cardio"],
    equipment: ["none"],
    difficulty: "advanced",
    instructions: "1. Sprint at maximum effort\n2. Rest between sprints\n3. Repeat for set time\n4. Maintain form",
    sets: "6",
    reps: "0",
    duration: "30 seconds sprint, 60 seconds rest",
    calories: 15
  },
  {
    name: "Plyometric Push-ups",
    type: "bodyweight",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["none"],
    difficulty: "advanced",
    instructions: "1. Perform push-up explosively\n2. Push hands off ground\n3. Land softly\n4. Repeat immediately",
    sets: "4",
    reps: "8-12",
    calories: 12
  },
  {
    name: "Clean & Press",
    type: "strength",
    muscleGroups: ["full body"],
    equipment: ["barbell"],
    difficulty: "advanced",
    instructions: "1. Clean bar to shoulders\n2. Press overhead\n3. Lower with control\n4. Return to start",
    sets: "4",
    reps: "5-8",
    calories: 15
  },
  {
    name: "Weighted Pull-ups",
    type: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["pull-up bar", "weight"],
    difficulty: "advanced",
    instructions: "1. Add weight to body\n2. Pull chin over bar\n3. Lower with control\n4. Don't swing",
    sets: "4",
    reps: "6-10",
    calories: 12
  },
  {
    name: "Snatch",
    type: "strength",
    muscleGroups: ["full body"],
    equipment: ["barbell"],
    difficulty: "advanced",
    instructions: "1. Explosive lift overhead\n2. Catch in squat position\n3. Stand up\n4. Lower with control",
    sets: "3",
    reps: "3-6",
    calories: 18
  },
  {
    name: "Turkish Get-ups",
    type: "strength",
    muscleGroups: ["full body"],
    equipment: ["kettlebell"],
    difficulty: "advanced",
    instructions: "1. Lie with kettlebell overhead\n2. Stand up while keeping weight up\n3. Reverse movement\n4. Control throughout",
    sets: "3",
    reps: "3-5 per side",
    calories: 12
  },
  {
    name: "Pistol Squats",
    type: "bodyweight",
    muscleGroups: ["legs", "glutes"],
    equipment: ["none"],
    difficulty: "advanced",
    instructions: "1. Stand on one leg\n2. Squat down on standing leg\n3. Keep other leg extended\n4. Stand back up",
    sets: "4",
    reps: "5-10 per leg",
    calories: 12
  },
  {
    name: "Single-leg Deadlifts",
    type: "strength",
    muscleGroups: ["back", "legs", "glutes"],
    equipment: ["dumbbells"],
    difficulty: "advanced",
    instructions: "1. Stand on one leg\n2. Hinge at hip\n3. Lower weight to ground\n4. Return to start",
    sets: "4",
    reps: "8-12 per leg",
    calories: 10
  },
  {
    name: "L-sit Hold",
    type: "bodyweight",
    muscleGroups: ["core", "shoulders"],
    equipment: ["parallel bars"],
    difficulty: "advanced",
    instructions: "1. Support on parallel bars\n2. Lift legs to horizontal\n3. Hold position\n4. Keep body straight",
    sets: "4",
    reps: "0",
    duration: "30-60 seconds",
    calories: 8
  },
  {
    name: "Dragon Flags",
    type: "bodyweight",
    muscleGroups: ["core"],
    equipment: ["bench"],
    difficulty: "advanced",
    instructions: "1. Lie on bench\n2. Hold bench behind head\n3. Raise entire body\n4. Lower with control",
    sets: "3",
    reps: "5-10",
    calories: 10
  },
  {
    name: "Glute Bridges",
    type: "bodyweight",
    muscleGroups: ["glutes", "core"],
    equipment: ["none"],
    difficulty: "beginner",
    instructions: "1. Lie on back with knees bent\n2. Lift hips to ceiling\n3. Squeeze glutes\n4. Lower with control",
    sets: "3",
    reps: "15-20",
    calories: 5
  },
  {
    name: "Pull-ups",
    type: "bodyweight",
    muscleGroups: ["back", "biceps"],
    equipment: ["pull-up bar"],
    difficulty: "intermediate",
    instructions: "1. Hang from bar\n2. Pull chin over bar\n3. Lower with control\n4. Don't swing",
    sets: "3",
    reps: "5-15",
    calories: 10
  },
  {
    name: "Incline Press",
    type: "strength",
    muscleGroups: ["chest", "shoulders"],
    equipment: ["barbell", "incline bench"],
    difficulty: "intermediate",
    instructions: "1. Set bench to 30-45 degrees\n2. Press bar from upper chest\n3. Lower with control\n4. Focus on upper chest",
    sets: "3",
    reps: "8-12",
    calories: 11
  },
  {
    name: "Dips",
    type: "bodyweight",
    muscleGroups: ["chest", "triceps", "shoulders"],
    equipment: ["dip bars"],
    difficulty: "intermediate",
    instructions: "1. Support on dip bars\n2. Lower body down\n3. Push back up\n4. Keep elbows close",
    sets: "3",
    reps: "8-15",
    calories: 10
  },
  {
    name: "Tricep Extensions",
    type: "strength",
    muscleGroups: ["triceps"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Extend arms overhead\n2. Lower weight behind head\n3. Extend back up\n4. Keep elbows steady",
    sets: "3",
    reps: "12-15",
    calories: 5
  },
  {
    name: "Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Raise arms to sides\n2. Keep slight bend in elbows\n3. Lower with control\n4. Don't swing",
    sets: "3",
    reps: "12-15",
    calories: 5
  },
  {
    name: "Decline Press",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["barbell", "decline bench"],
    difficulty: "intermediate",
    instructions: "1. Lie on decline bench\n2. Press bar from lower chest\n3. Lower with control\n4. Focus on lower chest",
    sets: "3",
    reps: "8-12",
    calories: 11
  },
  {
    name: "Weighted Dips",
    type: "strength",
    muscleGroups: ["chest", "triceps", "shoulders"],
    equipment: ["dip bars", "weight"],
    difficulty: "advanced",
    instructions: "1. Add weight to body\n2. Perform dips\n3. Keep form strict\n4. Control movement",
    sets: "4",
    reps: "6-12",
    calories: 12
  },
  {
    name: "Close-grip Bench",
    type: "strength",
    muscleGroups: ["chest", "triceps"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
    instructions: "1. Grip bar closer than shoulder-width\n2. Press bar from chest\n3. Lower with control\n4. Focus on triceps",
    sets: "3",
    reps: "8-12",
    calories: 10
  },
  {
    name: "T-bar Rows",
    type: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["t-bar row machine"],
    difficulty: "intermediate",
    instructions: "1. Straddle t-bar\n2. Pull bar to chest\n3. Squeeze shoulder blades\n4. Lower with control",
    sets: "3",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Preacher Curls",
    type: "strength",
    muscleGroups: ["biceps"],
    equipment: ["barbell", "preacher bench"],
    difficulty: "intermediate",
    instructions: "1. Rest arms on preacher bench\n2. Curl bar up\n3. Lower with control\n4. Keep arms steady",
    sets: "3",
    reps: "10-15",
    calories: 6
  },
  {
    name: "Romanian Deadlifts",
    type: "strength",
    muscleGroups: ["back", "legs", "glutes"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Hinge at hips\n2. Lower bar down legs\n3. Feel hamstring stretch\n4. Return to start",
    sets: "3",
    reps: "8-12",
    calories: 10
  }
];

// Helper function to generate template IDs
export const generateTemplateId = (name) => {
  return name.toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_')
    .trim();
};

// Helper function to add template IDs to exercises
export const allExercisesWithIds = allExercises.map(exercise => ({
  ...exercise,
  templateId: `${generateTemplateId(exercise.name)}_${Math.floor(Math.random() * 900) + 100}`
})); 