// SHOULDER EXERCISES (Primary: Deltoids - Anterior, Lateral, Posterior) - 50+ exercises

export const shoulderExercises = [
  // ANTERIOR DELTOID EXERCISES
  {
    name: "Military Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Hold barbell at shoulder level\n2. Press bar overhead\n3. Lower with control\n4. Keep core engaged",
    sets: "3-4",
    reps: "8-12",
    calories: 10
  },
  {
    name: "Arnold Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Start with dumbbells at shoulder level\n2. Rotate wrists and press overhead\n3. Reverse motion on way down\n4. Keep core engaged",
    sets: "3-4",
    reps: "8-12",
    calories: 10
  },
  {
    name: "Dumbbell Shoulder Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells at shoulder level\n2. Press dumbbells overhead\n3. Lower with control\n4. Keep core engaged",
    sets: "3-4",
    reps: "8-12",
    calories: 10
  },
  {
    name: "Seated Dumbbell Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells", "bench"],
    difficulty: "intermediate",
    instructions: "1. Sit on bench with dumbbells at shoulders\n2. Press dumbbells overhead\n3. Lower with control\n4. Keep back against bench",
    sets: "3-4",
    reps: "8-12",
    calories: 10
  },
  {
    name: "Standing Dumbbell Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Stand with dumbbells at shoulders\n2. Press dumbbells overhead\n3. Lower with control\n4. Keep core engaged",
    sets: "3-4",
    reps: "8-12",
    calories: 10
  },
  {
    name: "Push Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["barbell"],
    difficulty: "advanced",
    instructions: "1. Hold barbell at shoulder level\n2. Dip slightly and press overhead\n3. Lower with control\n4. Use leg drive for power",
    sets: "3-4",
    reps: "5-8",
    calories: 12
  },
  {
    name: "Dumbbell Push Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "advanced",
    instructions: "1. Hold dumbbells at shoulders\n2. Dip slightly and press overhead\n3. Lower with control\n4. Use leg drive for power",
    sets: "3-4",
    reps: "5-8",
    calories: 12
  },
  {
    name: "Landmine Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["barbell", "landmine"],
    difficulty: "intermediate",
    instructions: "1. Hold barbell end in both hands\n2. Press barbell forward and up\n3. Return to starting position\n4. Focus on shoulder activation",
    sets: "3-4",
    reps: "10-15",
    calories: 9
  },
  {
    name: "Single-Arm Landmine Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["barbell", "landmine"],
    difficulty: "intermediate",
    instructions: "1. Hold barbell end in one hand\n2. Press barbell forward and up\n3. Return to starting position\n4. Focus on unilateral strength",
    sets: "3-4",
    reps: "8-12 per arm",
    calories: 9
  },
  {
    name: "Machine Shoulder Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["shoulder press machine"],
    difficulty: "beginner",
    instructions: "1. Sit in shoulder press machine\n2. Press handles overhead\n3. Return to starting position\n4. Keep back against seat",
    sets: "3-4",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Smith Machine Shoulder Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["smith machine"],
    difficulty: "intermediate",
    instructions: "1. Set up barbell at shoulder level\n2. Press bar overhead\n3. Return to starting position\n4. Keep core engaged",
    sets: "3-4",
    reps: "8-12",
    calories: 9
  },
  {
    name: "Cable Shoulder Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cable at shoulder height\n2. Press cable overhead\n3. Return to starting position\n4. Keep tension throughout",
    sets: "3-4",
    reps: "10-15",
    calories: 8
  },
  {
    name: "Resistance Band Shoulder Press",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["resistance band"],
    difficulty: "beginner",
    instructions: "1. Stand on resistance band\n2. Hold band at shoulder level\n3. Press band overhead\n4. Keep tension throughout",
    sets: "3-4",
    reps: "15-20",
    calories: 6
  },
  {
    name: "Pike Push-Ups",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    instructions: "1. Form inverted V shape with hips high\n2. Lower head toward ground\n3. Push back up to starting position\n4. Focus on shoulder activation",
    sets: "3-4",
    reps: "8-15",
    calories: 9
  },
  {
    name: "Handstand Push-Ups",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["bodyweight", "wall"],
    difficulty: "advanced",
    instructions: "1. Kick up into handstand against wall\n2. Lower head toward ground\n3. Push back up to starting position\n4. Focus on shoulder strength",
    sets: "3",
    reps: "3-8",
    calories: 15
  },
  {
    name: "Decline Push-Ups",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    instructions: "1. Place feet on elevated surface\n2. Perform push-up with body at decline angle\n3. Lower chest to ground\n4. Focus on shoulder activation",
    sets: "3-4",
    reps: "8-15",
    calories: 10
  },
  {
    name: "Dips",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dip bars"],
    difficulty: "intermediate",
    instructions: "1. Support body on dip bars\n2. Lower body by bending elbows\n3. Push back up to starting position\n4. Keep body upright",
    sets: "3-4",
    reps: "8-15",
    calories: 10
  },
  {
    name: "Ring Dips",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["gymnastic rings"],
    difficulty: "advanced",
    instructions: "1. Support body on rings\n2. Lower body by bending elbows\n3. Push back up to starting position\n4. Maintain ring stability",
    sets: "3-4",
    reps: "5-12",
    calories: 12
  },
  {
    name: "Pike Push-Ups on Rings",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["gymnastic rings"],
    difficulty: "advanced",
    instructions: "1. Set rings at waist height\n2. Form pike position with feet elevated\n3. Lower head toward ground\n4. Push back up to starting position",
    sets: "3-4",
    reps: "5-10",
    calories: 11
  },
  {
    name: "Wall Walks",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["bodyweight", "wall"],
    difficulty: "advanced",
    instructions: "1. Start in plank position near wall\n2. Walk feet up wall while walking hands toward wall\n3. Return to starting position\n4. Focus on shoulder control",
    sets: "3",
    reps: "3-8",
    calories: 12
  },

  // LATERAL DELTOID EXERCISES
  {
    name: "Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Hold dumbbells at sides\n2. Raise arms to sides until parallel\n3. Lower with control\n4. Keep slight bend in elbows",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Seated Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner",
    instructions: "1. Sit on bench with dumbbells at sides\n2. Raise arms to sides until parallel\n3. Lower with control\n4. Keep slight bend in elbows",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Cable Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cable at low position\n2. Raise cable to side until parallel\n3. Return to starting position\n4. Keep tension throughout",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Single-Arm Cable Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cable at low position\n2. Raise cable to side with one arm\n3. Return to starting position\n4. Focus on unilateral strength",
    sets: "3-4",
    reps: "10-15 per arm",
    calories: 6
  },
  {
    name: "Machine Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["lateral raise machine"],
    difficulty: "beginner",
    instructions: "1. Sit in lateral raise machine\n2. Raise arms to sides until parallel\n3. Return to starting position\n4. Keep back against seat",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Resistance Band Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["resistance band"],
    difficulty: "beginner",
    instructions: "1. Stand on resistance band\n2. Hold band at sides\n3. Raise arms to sides until parallel\n4. Keep tension throughout",
    sets: "3-4",
    reps: "15-25",
    calories: 5
  },
  {
    name: "Bent-Over Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Bend at hips with dumbbells hanging\n2. Raise arms to sides until parallel\n3. Lower with control\n4. Keep back straight",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Prone Lateral Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner",
    instructions: "1. Lie face down on incline bench\n2. Raise arms to sides until parallel\n3. Lower with control\n4. Focus on shoulder activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Lateral Raises with Rotation",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells at sides\n2. Raise arms to sides with rotation\n3. Lower with control\n4. Focus on full range of motion",
    sets: "3-4",
    reps: "12-20",
    calories: 7
  },
  {
    name: "Y-Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells at sides\n2. Raise arms in Y position\n3. Lower with control\n4. Focus on upper trap activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "T-Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells at sides\n2. Raise arms in T position\n3. Lower with control\n4. Focus on middle trap activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "W-Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells at sides\n2. Raise arms in W position\n3. Lower with control\n4. Focus on rhomboid activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "I-Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells at sides\n2. Raise arms straight overhead\n3. Lower with control\n4. Focus on full shoulder activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Front Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Hold dumbbells in front of thighs\n2. Raise arms forward until parallel\n3. Lower with control\n4. Keep slight bend in elbows",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Cable Front Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cable at low position\n2. Raise cable forward until parallel\n3. Return to starting position\n4. Keep tension throughout",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Plate Front Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["weight plate"],
    difficulty: "beginner",
    instructions: "1. Hold weight plate in front of thighs\n2. Raise plate forward until parallel\n3. Lower with control\n4. Keep slight bend in elbows",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Barbell Front Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Hold barbell in front of thighs\n2. Raise barbell forward until parallel\n3. Lower with control\n4. Keep slight bend in elbows",
    sets: "3-4",
    reps: "10-15",
    calories: 7
  },
  {
    name: "Alternating Front Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells in front of thighs\n2. Raise one arm forward until parallel\n3. Lower and alternate arms\n4. Keep slight bend in elbows",
    sets: "3-4",
    reps: "10-15 per arm",
    calories: 7
  },
  {
    name: "Upright Rows",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Hold barbell with close grip\n2. Pull bar up to chin level\n3. Lower with control\n4. Keep elbows high",
    sets: "3-4",
    reps: "10-12",
    calories: 8
  },
  {
    name: "Dumbbell Upright Rows",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    instructions: "1. Hold dumbbells with close grip\n2. Pull dumbbells up to chin level\n3. Lower with control\n4. Keep elbows high",
    sets: "3-4",
    reps: "10-12",
    calories: 8
  },
  {
    name: "Cable Upright Rows",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cable at low position\n2. Pull cable up to chin level\n3. Return to starting position\n4. Keep elbows high",
    sets: "3-4",
    reps: "10-15",
    calories: 7
  },
  {
    name: "Resistance Band Upright Rows",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["resistance band"],
    difficulty: "beginner",
    instructions: "1. Stand on resistance band\n2. Hold band with close grip\n3. Pull band up to chin level\n4. Keep tension throughout",
    sets: "3-4",
    reps: "15-20",
    calories: 6
  },
  {
    name: "Shrugs",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Hold dumbbells at sides\n2. Shrug shoulders up toward ears\n3. Lower with control\n4. Focus on trap activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Barbell Shrugs",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Hold barbell in front of thighs\n2. Shrug shoulders up toward ears\n3. Lower with control\n4. Focus on trap activation",
    sets: "3-4",
    reps: "10-15",
    calories: 7
  },
  {
    name: "Behind-the-Back Shrugs",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    instructions: "1. Hold barbell behind back\n2. Shrug shoulders up toward ears\n3. Lower with control\n4. Focus on trap activation",
    sets: "3-4",
    reps: "10-15",
    calories: 7
  },
  {
    name: "Cable Shrugs",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "intermediate",
    instructions: "1. Set cable at low position\n2. Hold cable and shrug shoulders\n3. Return to starting position\n4. Focus on trap activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Resistance Band Shrugs",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["resistance band"],
    difficulty: "beginner",
    instructions: "1. Stand on resistance band\n2. Hold band at sides\n3. Shrug shoulders up\n4. Keep tension throughout",
    sets: "3-4",
    reps: "15-25",
    calories: 5
  },
  {
    name: "Face Pulls",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "beginner",
    instructions: "1. Set cable at face height\n2. Pull cable toward face\n3. Return to starting position\n4. Focus on rear delt activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Reverse Flyes",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Bend at hips with dumbbells hanging\n2. Raise arms to sides\n3. Lower with control\n4. Focus on rear delt activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Cable Reverse Flyes",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "beginner",
    instructions: "1. Set cables at chest height\n2. Pull cables to sides\n3. Return to starting position\n4. Focus on rear delt activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Machine Reverse Flyes",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["reverse flye machine"],
    difficulty: "beginner",
    instructions: "1. Sit in reverse flye machine\n2. Pull arms to sides\n3. Return to starting position\n4. Focus on rear delt activation",
    sets: "3-4",
    reps: "12-20",
    calories: 6
  },
  {
    name: "Band Pull-Aparts",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["resistance band"],
    difficulty: "beginner",
    instructions: "1. Hold band at chest height\n2. Pull band apart\n3. Return to starting position\n4. Focus on rear delt activation",
    sets: "3-4",
    reps: "15-25",
    calories: 5
  },
  {
    name: "Prone Y-Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Lie face down on bench\n2. Raise arms in Y position\n3. Lower with control\n4. Focus on lower trap activation",
    sets: "3-4",
    reps: "12-20",
    calories: 5
  },
  {
    name: "Prone T-Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Lie face down on bench\n2. Raise arms in T position\n3. Lower with control\n4. Focus on middle trap activation",
    sets: "3-4",
    reps: "12-20",
    calories: 5
  },
  {
    name: "Prone W-Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Lie face down on bench\n2. Raise arms in W position\n3. Lower with control\n4. Focus on rhomboid activation",
    sets: "3-4",
    reps: "12-20",
    calories: 5
  },
  {
    name: "Prone I-Raises",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    instructions: "1. Lie face down on bench\n2. Raise arms straight overhead\n3. Lower with control\n4. Focus on full shoulder activation",
    sets: "3-4",
    reps: "12-20",
    calories: 5
  },
  {
    name: "Scapular Pull-Ups",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["pull-up bar"],
    difficulty: "beginner",
    instructions: "1. Hang from pull-up bar\n2. Pull shoulder blades down\n3. Return to starting position\n4. Focus on scapular control",
    sets: "3-4",
    reps: "10-15",
    calories: 5
  },
  {
    name: "Scapular Rows",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["cable machine"],
    difficulty: "beginner",
    instructions: "1. Sit at cable row machine\n2. Pull shoulder blades together\n3. Return to starting position\n4. Focus on scapular retraction",
    sets: "3-4",
    reps: "12-20",
    calories: 5
  },
  {
    name: "Wall Angels",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    instructions: "1. Stand with back against wall\n2. Slide arms up and down wall\n3. Keep contact with wall\n4. Focus on shoulder mobility",
    sets: "3",
    reps: "10-15",
    calories: 3
  },
  {
    name: "Shoulder Stretch",
    type: "flexibility",
    muscleGroups: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    instructions: "1. Cross one arm across chest\n2. Hold with opposite arm\n3. Hold stretch for 30 seconds\n4. Repeat on other side",
    sets: "3",
    reps: "30-60 seconds per side",
    calories: 2
  },
  {
    name: "Foam Rolling Shoulders",
    type: "recovery",
    muscleGroups: ["shoulders"],
    equipment: ["foam roller"],
    difficulty: "beginner",
    instructions: "1. Lie on foam roller lengthwise\n2. Roll over shoulder muscles\n3. Focus on tight areas\n4. Spend 1-2 minutes per side",
    sets: "1",
    reps: "2-3 minutes per side",
    calories: 2
  }
]; 